name: fire_incidents

profile: 'profile_for_local_deployment'
config-version: 2

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"

models:
  fire_incidents:
  +schema: rendered_models
  +materialized: table