profile_for_local_deployment:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"

      