version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: fire-incidents-postgres-container
    env_file: .env
    ports:
      - "5432:5432"
  
  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    env_file: .env
    volumes:
      - ../scripts:/usr/src/app/scripts
      - ./requirements.txt:/usr/src/app/requirements.txt
      - ../sql:/usr/src/app/sql
    command: ["cron", "-f"]

  dbt:
    build:
      context: .
      dockerfile: dbt/Dockerfile
    env_file: .env
    volumes:
      - ../dbt:/usr/src/app/dbt
    depends_on:
      - postgres
    command: ["cron", "-f"]