version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: fire-incidents-postgres-container
    env_file: .env
    ports:
      - "5432:5432"
  
  cron:
    build: .
    volumes:
      - ./scripts/ingest_data.py:/usr/src/app/scripts/ingest_data.py
      - ./requirements.txt:/usr/src/app/requirements.txt
    command: cron -f