version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: fire-incidents-postgres-container
    env_file: .env
    ports:
      - "5432:5432"
  
  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    volumes:
      - ../scripts:/usr/src/app/scripts
      - ./requirements.txt:/usr/src/app/requirements.txt
    command: ["cron", "-f"]